// Country data with phone codes and validation patterns
export const COUNTRIES = [
    { code: 'AE', name: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة', dialCode: '+971', flag: '🇦🇪', pattern: /^[0-9]{9}$/, timezone: 'Asia/Dubai' },
    { code: 'SA', name: 'Saudi Arabia', nameAr: 'المملكة العربية السعودية', dialCode: '+966', flag: '🇸🇦', pattern: /^[0-9]{9}$/, timezone: 'Asia/Riyadh' },
    { code: 'QA', name: 'Qatar', nameAr: 'قطر', dialCode: '+974', flag: '🇶🇦', pattern: /^[0-9]{8}$/, timezone: 'Asia/Qatar' },
    { code: 'KW', name: 'Kuwait', nameAr: 'الكويت', dialCode: '+965', flag: '🇰🇼', pattern: /^[0-9]{8}$/, timezone: 'Asia/Kuwait' },
    { code: 'BH', name: 'Bahrain', nameAr: 'البحرين', dialCode: '+973', flag: '🇧🇭', pattern: /^[0-9]{8}$/, timezone: 'Asia/Bahrain' },
    { code: 'OM', name: 'Oman', nameAr: 'عُمان', dialCode: '+968', flag: '🇴🇲', pattern: /^[0-9]{8}$/, timezone: 'Asia/Muscat' },
    { code: 'US', name: 'United States', nameAr: 'الولايات المتحدة', dialCode: '+1', flag: '🇺🇸', pattern: /^[0-9]{10}$/, timezone: 'America/New_York' },
    { code: 'GB', name: 'United Kingdom', nameAr: 'المملكة المتحدة', dialCode: '+44', flag: '🇬🇧', pattern: /^[0-9]{10,11}$/, timezone: 'Europe/London' },
    { code: 'IN', name: 'India', nameAr: 'الهند', dialCode: '+91', flag: '🇮🇳', pattern: /^[0-9]{10}$/, timezone: 'Asia/Kolkata' }
];


// export const COUNTRIES = [
//     { code: 'AF', name: 'Afghanistan', nameAr: 'أفغانستان', dialCode: '+93', flag: '🇦🇫', pattern: /^[0-9]{9}$/, timezone: 'Asia/Kabul' },
//     { code: 'AL', name: 'Albania', nameAr: 'ألبانيا', dialCode: '+355', flag: '🇦🇱', pattern: /^[0-9]{9}$/, timezone: 'Europe/Tirane' },
//     { code: 'DZ', name: 'Algeria', nameAr: 'الجزائر', dialCode: '+213', flag: '🇩🇿', pattern: /^[0-9]{9}$/, timezone: 'Africa/Algiers' },
//     { code: 'AD', name: 'Andorra', nameAr: 'أندورا', dialCode: '+376', flag: '🇦🇩', pattern: /^[0-9]{6,8}$/, timezone: 'Europe/Andorra' },
//     { code: 'AO', name: 'Angola', nameAr: 'أنغولا', dialCode: '+244', flag: '🇦🇴', pattern: /^[0-9]{9}$/, timezone: 'Africa/Luanda' },
//     { code: 'AG', name: 'Antigua and Barbuda', nameAr: 'أنتيغوا وباربودا', dialCode: '+1268', flag: '🇦🇬', pattern: /^[0-9]{7}$/, timezone: 'America/Antigua' },
//     { code: 'AR', name: 'Argentina', nameAr: 'الأرجنتين', dialCode: '+54', flag: '🇦🇷', pattern: /^[0-9]{10}$/, timezone: 'America/Argentina/Buenos_Aires' },
//     { code: 'AM', name: 'Armenia', nameAr: 'أرمينيا', dialCode: '+374', flag: '🇦🇲', pattern: /^[0-9]{8}$/, timezone: 'Asia/Yerevan' },
//     { code: 'AU', name: 'Australia', nameAr: 'أستراليا', dialCode: '+61', flag: '🇦🇺', pattern: /^[0-9]{9,10}$/, timezone: 'Australia/Sydney' },
//     { code: 'AT', name: 'Austria', nameAr: 'النمسا', dialCode: '+43', flag: '🇦🇹', pattern: /^[0-9]{10,11}$/, timezone: 'Europe/Vienna' },
//     { code: 'AZ', name: 'Azerbaijan', nameAr: 'أذربيجان', dialCode: '+994', flag: '🇦🇿', pattern: /^[0-9]{9}$/, timezone: 'Asia/Baku' },
//     { code: 'BS', name: 'Bahamas', nameAr: 'جزر البهاما', dialCode: '+1242', flag: '🇧🇸', pattern: /^[0-9]{7}$/, timezone: 'America/Nassau' },
//     { code: 'BH', name: 'Bahrain', nameAr: 'البحرين', dialCode: '+973', flag: '🇧🇭', pattern: /^[0-9]{8}$/, timezone: 'Asia/Bahrain' },
//     { code: 'BD', name: 'Bangladesh', nameAr: 'بنغلاديش', dialCode: '+880', flag: '🇧🇩', pattern: /^[0-9]{10}$/, timezone: 'Asia/Dhaka' },
//     { code: 'BB', name: 'Barbados', nameAr: 'باربادوس', dialCode: '+1246', flag: '🇧🇧', pattern: /^[0-9]{7}$/, timezone: 'America/Barbados' },
//     { code: 'BY', name: 'Belarus', nameAr: 'بيلاروسيا', dialCode: '+375', flag: '🇧🇾', pattern: /^[0-9]{9}$/, timezone: 'Europe/Minsk' },
//     { code: 'BE', name: 'Belgium', nameAr: 'بلجيكا', dialCode: '+32', flag: '🇧🇪', pattern: /^[0-9]{9}$/, timezone: 'Europe/Brussels' },
//     { code: 'BZ', name: 'Belize', nameAr: 'بليز', dialCode: '+501', flag: '🇧🇿', pattern: /^[0-9]{7}$/, timezone: 'America/Belize' },
//     { code: 'BJ', name: 'Benin', nameAr: 'بنين', dialCode: '+229', flag: '🇧🇯', pattern: /^[0-9]{8}$/, timezone: 'Africa/Porto-Novo' },
//     { code: 'BT', name: 'Bhutan', nameAr: 'بوتان', dialCode: '+975', flag: '🇧🇹', pattern: /^[0-9]{8}$/, timezone: 'Asia/Thimphu' },
//     { code: 'BO', name: 'Bolivia', nameAr: 'بوليفيا', dialCode: '+591', flag: '🇧🇴', pattern: /^[0-9]{8}$/, timezone: 'America/La_Paz' },
//     { code: 'BA', name: 'Bosnia and Herzegovina', nameAr: 'البوسنة والهرسك', dialCode: '+387', flag: '🇧🇦', pattern: /^[0-9]{8,9}$/, timezone: 'Europe/Sarajevo' },
//     { code: 'BW', name: 'Botswana', nameAr: 'بوتسوانا', dialCode: '+267', flag: '🇧🇼', pattern: /^[0-9]{7,8}$/, timezone: 'Africa/Gaborone' },
//     { code: 'BR', name: 'Brazil', nameAr: 'البرازيل', dialCode: '+55', flag: '🇧🇷', pattern: /^[0-9]{10,11}$/, timezone: 'America/Sao_Paulo' },
//     { code: 'BN', name: 'Brunei', nameAr: 'بروناي', dialCode: '+673', flag: '🇧🇳', pattern: /^[0-9]{7}$/, timezone: 'Asia/Brunei' },
//     { code: 'BG', name: 'Bulgaria', nameAr: 'بلغاريا', dialCode: '+359', flag: '🇧🇬', pattern: /^[0-9]{9}$/, timezone: 'Europe/Sofia' },
//     { code: 'BF', name: 'Burkina Faso', nameAr: 'بوركينا فاسو', dialCode: '+226', flag: '🇧🇫', pattern: /^[0-9]{8}$/, timezone: 'Africa/Ouagadougou' },
//     { code: 'BI', name: 'Burundi', nameAr: 'بوروندي', dialCode: '+257', flag: '🇧🇮', pattern: /^[0-9]{8}$/, timezone: 'Africa/Bujumbura' },
//     { code: 'CV', name: 'Cabo Verde', nameAr: 'الرأس الأخضر', dialCode: '+238', flag: '🇨🇻', pattern: /^[0-9]{7}$/, timezone: 'Atlantic/Cape_Verde' },
//     { code: 'KH', name: 'Cambodia', nameAr: 'كمبوديا', dialCode: '+855', flag: '🇰🇭', pattern: /^[0-9]{8,9}$/, timezone: 'Asia/Phnom_Penh' },
//     { code: 'CM', name: 'Cameroon', nameAr: 'الكاميرون', dialCode: '+237', flag: '🇨🇲', pattern: /^[0-9]{9}$/, timezone: 'Africa/Douala' },
//     { code: 'CA', name: 'Canada', nameAr: 'كندا', dialCode: '+1', flag: '🇨🇦', pattern: /^[0-9]{10}$/, timezone: 'America/Toronto' },
//     { code: 'CF', name: 'Central African Republic', nameAr: 'جمهورية أفريقيا الوسطى', dialCode: '+236', flag: '🇨🇫', pattern: /^[0-9]{8}$/, timezone: 'Africa/Bangui' },
//     { code: 'TD', name: 'Chad', nameAr: 'تشاد', dialCode: '+235', flag: '🇹🇩', pattern: /^[0-9]{8}$/, timezone: 'Africa/Ndjamena' },
//     { code: 'CL', name: 'Chile', nameAr: 'تشيلي', dialCode: '+56', flag: '🇨🇱', pattern: /^[0-9]{9}$/, timezone: 'America/Santiago' },
//     { code: 'CN', name: 'China', nameAr: 'الصين', dialCode: '+86', flag: '🇨🇳', pattern: /^[0-9]{11}$/, timezone: 'Asia/Shanghai' },
//     { code: 'CO', name: 'Colombia', nameAr: 'كولومبيا', dialCode: '+57', flag: '🇨🇴', pattern: /^[0-9]{10}$/, timezone: 'America/Bogota' },
//     { code: 'KM', name: 'Comoros', nameAr: 'جزر القمر', dialCode: '+269', flag: '🇰🇲', pattern: /^[0-9]{7}$/, timezone: 'Indian/Comoro' },
//     { code: 'CG', name: 'Congo', nameAr: 'الكونغو', dialCode: '+242', flag: '🇨🇬', pattern: /^[0-9]{9}$/, timezone: 'Africa/Brazzaville' },
//     { code: 'CD', name: 'Congo (DRC)', nameAr: 'الكونغو الديمقراطية', dialCode: '+243', flag: '🇨🇩', pattern: /^[0-9]{9}$/, timezone: 'Africa/Kinshasa' },
//     { code: 'CR', name: 'Costa Rica', nameAr: 'كوستاريكا', dialCode: '+506', flag: '🇨🇷', pattern: /^[0-9]{8}$/, timezone: 'America/Costa_Rica' },
//     { code: 'HR', name: 'Croatia', nameAr: 'كرواتيا', dialCode: '+385', flag: '🇭🇷', pattern: /^[0-9]{8,9}$/, timezone: 'Europe/Zagreb' },
//     { code: 'CU', name: 'Cuba', nameAr: 'كوبا', dialCode: '+53', flag: '🇨🇺', pattern: /^[0-9]{8}$/, timezone: 'America/Havana' },
//     { code: 'CY', name: 'Cyprus', nameAr: 'قبرص', dialCode: '+357', flag: '🇨🇾', pattern: /^[0-9]{8}$/, timezone: 'Asia/Nicosia' },
//     { code: 'CZ', name: 'Czech Republic', nameAr: 'جمهورية التشيك', dialCode: '+420', flag: '🇨🇿', pattern: /^[0-9]{9}$/, timezone: 'Europe/Prague' },
//     { code: 'DK', name: 'Denmark', nameAr: 'الدنمارك', dialCode: '+45', flag: '🇩🇰', pattern: /^[0-9]{8}$/, timezone: 'Europe/Copenhagen' },
//     { code: 'DJ', name: 'Djibouti', nameAr: 'جيبوتي', dialCode: '+253', flag: '🇩🇯', pattern: /^[0-9]{8}$/, timezone: 'Africa/Djibouti' },
//     { code: 'DM', name: 'Dominica', nameAr: 'دومينيكا', dialCode: '+1767', flag: '🇩🇲', pattern: /^[0-9]{7}$/, timezone: 'America/Dominica' },
//     { code: 'DO', name: 'Dominican Republic', nameAr: 'جمهورية الدومينيكان', dialCode: '+1809', flag: '🇩🇴', pattern: /^[0-9]{7}$/, timezone: 'America/Santo_Domingo' },
//     { code: 'EC', name: 'Ecuador', nameAr: 'الإكوادور', dialCode: '+593', flag: '🇪🇨', pattern: /^[0-9]{9}$/, timezone: 'America/Guayaquil' },
//     { code: 'EG', name: 'Egypt', nameAr: 'مصر', dialCode: '+20', flag: '🇪🇬', pattern: /^[0-9]{10}$/, timezone: 'Africa/Cairo' },
//     { code: 'SV', name: 'El Salvador', nameAr: 'السلفادور', dialCode: '+503', flag: '🇸🇻', pattern: /^[0-9]{8}$/, timezone: 'America/El_Salvador' },
//     { code: 'GQ', name: 'Equatorial Guinea', nameAr: 'غينيا الاستوائية', dialCode: '+240', flag: '🇬🇶', pattern: /^[0-9]{9}$/, timezone: 'Africa/Malabo' },
//     { code: 'ER', name: 'Eritrea', nameAr: 'إريتريا', dialCode: '+291', flag: '🇪🇷', pattern: /^[0-9]{7}$/, timezone: 'Africa/Asmara' },
//     { code: 'EE', name: 'Estonia', nameAr: 'إستونيا', dialCode: '+372', flag: '🇪🇪', pattern: /^[0-9]{7,8}$/, timezone: 'Europe/Tallinn' },
//     { code: 'SZ', name: 'Eswatini', nameAr: 'إسواتيني', dialCode: '+268', flag: '🇸🇿', pattern: /^[0-9]{8}$/, timezone: 'Africa/Mbabane' },
//     { code: 'ET', name: 'Ethiopia', nameAr: 'إثيوبيا', dialCode: '+251', flag: '🇪🇹', pattern: /^[0-9]{9}$/, timezone: 'Africa/Addis_Ababa' },
//     { code: 'FJ', name: 'Fiji', nameAr: 'فيجي', dialCode: '+679', flag: '🇫🇯', pattern: /^[0-9]{7}$/, timezone: 'Pacific/Fiji' },
//     { code: 'FI', name: 'Finland', nameAr: 'فنلندا', dialCode: '+358', flag: '🇫🇮', pattern: /^[0-9]{9,10}$/, timezone: 'Europe/Helsinki' },
//     { code: 'FR', name: 'France', nameAr: 'فرنسا', dialCode: '+33', flag: '🇫🇷', pattern: /^[0-9]{9}$/, timezone: 'Europe/Paris' },
//     { code: 'GA', name: 'Gabon', nameAr: 'الغابون', dialCode: '+241', flag: '🇬🇦', pattern: /^[0-9]{8}$/, timezone: 'Africa/Libreville' },
//     { code: 'GM', name: 'Gambia', nameAr: 'غامبيا', dialCode: '+220', flag: '🇬🇲', pattern: /^[0-9]{7}$/, timezone: 'Africa/Banjul' },
//     { code: 'GE', name: 'Georgia', nameAr: 'جورجيا', dialCode: '+995', flag: '🇬🇪', pattern: /^[0-9]{9}$/, timezone: 'Asia/Tbilisi' },
//     { code: 'DE', name: 'Germany', nameAr: 'ألمانيا', dialCode: '+49', flag: '🇩🇪', pattern: /^[0-9]{10,11}$/, timezone: 'Europe/Berlin' },
//     { code: 'GH', name: 'Ghana', nameAr: 'غانا', dialCode: '+233', flag: '🇬🇭', pattern: /^[0-9]{9}$/, timezone: 'Africa/Accra' },
//     { code: 'GR', name: 'Greece', nameAr: 'اليونان', dialCode: '+30', flag: '🇬🇷', pattern: /^[0-9]{10}$/, timezone: 'Europe/Athens' },
//     { code: 'GD', name: 'Grenada', nameAr: 'غرينادا', dialCode: '+1473', flag: '🇬🇩', pattern: /^[0-9]{7}$/, timezone: 'America/Grenada' },
//     { code: 'GT', name: 'Guatemala', nameAr: 'غواتيمالا', dialCode: '+502', flag: '🇬🇹', pattern: /^[0-9]{8}$/, timezone: 'America/Guatemala' },
//     { code: 'GN', name: 'Guinea', nameAr: 'غينيا', dialCode: '+224', flag: '🇬🇳', pattern: /^[0-9]{9}$/, timezone: 'Africa/Conakry' },
//     { code: 'GW', name: 'Guinea-Bissau', nameAr: 'غينيا بيساو', dialCode: '+245', flag: '🇬🇼', pattern: /^[0-9]{7}$/, timezone: 'Africa/Bissau' },
//     { code: 'GY', name: 'Guyana', nameAr: 'غيانا', dialCode: '+592', flag: '🇬🇾', pattern: /^[0-9]{7}$/, timezone: 'America/Guyana' },
//     { code: 'HT', name: 'Haiti', nameAr: 'هايتي', dialCode: '+509', flag: '🇭🇹', pattern: /^[0-9]{8}$/, timezone: 'America/Port-au-Prince' },
//     { code: 'HN', name: 'Honduras', nameAr: 'هندوراس', dialCode: '+504', flag: '🇭🇳', pattern: /^[0-9]{8}$/, timezone: 'America/Tegucigalpa' },
//     { code: 'HU', name: 'Hungary', nameAr: 'المجر', dialCode: '+36', flag: '🇭🇺', pattern: /^[0-9]{9}$/, timezone: 'Europe/Budapest' },
//     { code: 'IS', name: 'Iceland', nameAr: 'آيسلندا', dialCode: '+354', flag: '🇮🇸', pattern: /^[0-9]{7}$/, timezone: 'Atlantic/Reykjavik' },
//     { code: 'IN', name: 'India', nameAr: 'الهند', dialCode: '+91', flag: '🇮🇳', pattern: /^[0-9]{10}$/, timezone: 'Asia/Kolkata' },
//     { code: 'ID', name: 'Indonesia', nameAr: 'إندونيسيا', dialCode: '+62', flag: '🇮🇩', pattern: /^[0-9]{9,12}$/, timezone: 'Asia/Jakarta' },
//     { code: 'IR', name: 'Iran', nameAr: 'إيران', dialCode: '+98', flag: '🇮🇷', pattern: /^[0-9]{10}$/, timezone: 'Asia/Tehran' },
//     { code: 'IQ', name: 'Iraq', nameAr: 'العراق', dialCode: '+964', flag: '🇮🇶', pattern: /^[0-9]{10}$/, timezone: 'Asia/Baghdad' },
//     { code: 'IE', name: 'Ireland', nameAr: 'أيرلندا', dialCode: '+353', flag: '🇮🇪', pattern: /^[0-9]{9}$/, timezone: 'Europe/Dublin' },
//     { code: 'IL', name: 'Israel', nameAr: 'إسرائيل', dialCode: '+972', flag: '🇮🇱', pattern: /^[0-9]{9}$/, timezone: 'Asia/Jerusalem' },
//     { code: 'IT', name: 'Italy', nameAr: 'إيطاليا', dialCode: '+39', flag: '🇮🇹', pattern: /^[0-9]{9,10}$/, timezone: 'Europe/Rome' },
//     { code: 'JM', name: 'Jamaica', nameAr: 'جامايكا', dialCode: '+1876', flag: '🇯🇲', pattern: /^[0-9]{7}$/, timezone: 'America/Jamaica' },
//     { code: 'JP', name: 'Japan', nameAr: 'اليابان', dialCode: '+81', flag: '🇯🇵', pattern: /^[0-9]{10,11}$/, timezone: 'Asia/Tokyo' },
//     { code: 'JO', name: 'Jordan', nameAr: 'الأردن', dialCode: '+962', flag: '🇯🇴', pattern: /^[0-9]{9}$/, timezone: 'Asia/Amman' },
//     { code: 'KZ', name: 'Kazakhstan', nameAr: 'كازاخستان', dialCode: '+7', flag: '🇰🇿', pattern: /^[0-9]{10}$/, timezone: 'Asia/Almaty' },
//     { code: 'KE', name: 'Kenya', nameAr: 'كينيا', dialCode: '+254', flag: '🇰🇪', pattern: /^[0-9]{9}$/, timezone: 'Africa/Nairobi' },
//     { code: 'KI', name: 'Kiribati', nameAr: 'كيريباتي', dialCode: '+686', flag: '🇰🇮', pattern: /^[0-9]{8}$/, timezone: 'Pacific/Tarawa' },
//     { code: 'KP', name: 'North Korea', nameAr: 'كوريا الشمالية', dialCode: '+850', flag: '🇰🇵', pattern: /^[0-9]{10}$/, timezone: 'Asia/Pyongyang' },
//     { code: 'KR', name: 'South Korea', nameAr: 'كوريا الجنوبية', dialCode: '+82', flag: '🇰🇷', pattern: /^[0-9]{9,10}$/, timezone: 'Asia/Seoul' },
//     { code: 'KW', name: 'Kuwait', nameAr: 'الكويت', dialCode: '+965', flag: '🇰🇼', pattern: /^[0-9]{8}$/, timezone: 'Asia/Kuwait' },
//     { code: 'KG', name: 'Kyrgyzstan', nameAr: 'قيرغيزستان', dialCode: '+996', flag: '🇰🇬', pattern: /^[0-9]{9}$/, timezone: 'Asia/Bishkek' },
//     { code: 'LA', name: 'Laos', nameAr: 'لاوس', dialCode: '+856', flag: '🇱🇦', pattern: /^[0-9]{8,9}$/, timezone: 'Asia/Vientiane' },
//     { code: 'LV', name: 'Latvia', nameAr: 'لاتفيا', dialCode: '+371', flag: '🇱🇻', pattern: /^[0-9]{8}$/, timezone: 'Europe/Riga' },
//     { code: 'LB', name: 'Lebanon', nameAr: 'لبنان', dialCode: '+961', flag: '🇱🇧', pattern: /^[0-9]{7,8}$/, timezone: 'Asia/Beirut' },
//     { code: 'LS', name: 'Lesotho', nameAr: 'ليسوتو', dialCode: '+266', flag: '🇱🇸', pattern: /^[0-9]{8}$/, timezone: 'Africa/Maseru' },
//     { code: 'LR', name: 'Liberia', nameAr: 'ليبيريا', dialCode: '+231', flag: '🇱🇷', pattern: /^[0-9]{7,8}$/, timezone: 'Africa/Monrovia' },
//     { code: 'LY', name: 'Libya', nameAr: 'ليبيا', dialCode: '+218', flag: '🇱🇾', pattern: /^[0-9]{9}$/, timezone: 'Africa/Tripoli' },
//     { code: 'LI', name: 'Liechtenstein', nameAr: 'ليختنشتاين', dialCode: '+423', flag: '🇱🇮', pattern: /^[0-9]{7}$/, timezone: 'Europe/Vaduz' },
//     { code: 'LT', name: 'Lithuania', nameAr: 'ليتوانيا', dialCode: '+370', flag: '🇱🇹', pattern: /^[0-9]{8}$/, timezone: 'Europe/Vilnius' },
//     { code: 'LU', name: 'Luxembourg', nameAr: 'لوكسمبورغ', dialCode: '+352', flag: '🇱🇺', pattern: /^[0-9]{9}$/, timezone: 'Europe/Luxembourg' },
//     { code: 'MG', name: 'Madagascar', nameAr: 'مدغشقر', dialCode: '+261', flag: '🇲🇬', pattern: /^[0-9]{9}$/, timezone: 'Indian/Antananarivo' },
//     { code: 'MW', name: 'Malawi', nameAr: 'ملاوي', dialCode: '+265', flag: '🇲🇼', pattern: /^[0-9]{9}$/, timezone: 'Africa/Blantyre' },
//     { code: 'MY', name: 'Malaysia', nameAr: 'ماليزيا', dialCode: '+60', flag: '🇲🇾', pattern: /^[0-9]{9,10}$/, timezone: 'Asia/Kuala_Lumpur' },
//     { code: 'MV', name: 'Maldives', nameAr: 'جزر المالديف', dialCode: '+960', flag: '🇲🇻', pattern: /^[0-9]{7}$/, timezone: 'Indian/Maldives' },
//     { code: 'ML', name: 'Mali', nameAr: 'مالي', dialCode: '+223', flag: '🇲🇱', pattern: /^[0-9]{8}$/, timezone: 'Africa/Bamako' },
//     { code: 'MT', name: 'Malta', nameAr: 'مالطا', dialCode: '+356', flag: '🇲🇹', pattern: /^[0-9]{8}$/, timezone: 'Europe/Malta' },
//     { code: 'MH', name: 'Marshall Islands', nameAr: 'جزر مارشال', dialCode: '+692', flag: '🇲🇭', pattern: /^[0-9]{7}$/, timezone: 'Pacific/Majuro' },
//     { code: 'MR', name: 'Mauritania', nameAr: 'موريتانيا', dialCode: '+222', flag: '🇲🇷', pattern: /^[0-9]{8}$/, timezone: 'Africa/Nouakchott' },
//     { code: 'MU', name: 'Mauritius', nameAr: 'موريشيوس', dialCode: '+230', flag: '🇲🇺', pattern: /^[0-9]{8}$/, timezone: 'Indian/Mauritius' },
//     { code: 'MX', name: 'Mexico', nameAr: 'المكسيك', dialCode: '+52', flag: '🇲🇽', pattern: /^[0-9]{10}$/, timezone: 'America/Mexico_City' },
//     { code: 'FM', name: 'Micronesia', nameAr: 'ميكرونيزيا', dialCode: '+691', flag: '🇫🇲', pattern: /^[0-9]{7}$/, timezone: 'Pacific/Pohnpei' },
//     { code: 'MD', name: 'Moldova', nameAr: 'مولدوفا', dialCode: '+373', flag: '🇲🇩', pattern: /^[0-9]{8}$/, timezone: 'Europe/Chisinau' },
//     { code: 'MC', name: 'Monaco', nameAr: 'موناكو', dialCode: '+377', flag: '🇲🇨', pattern: /^[0-9]{8,9}$/, timezone: 'Europe/Monaco' },
//     { code: 'MN', name: 'Mongolia', nameAr: 'منغوليا', dialCode: '+976', flag: '🇲🇳', pattern: /^[0-9]{8}$/, timezone: 'Asia/Ulaanbaatar' },
//     { code: 'ME', name: 'Montenegro', nameAr: 'الجبل الأسود', dialCode: '+382', flag: '🇲🇪', pattern: /^[0-9]{8}$/, timezone: 'Europe/Podgorica' },
//     { code: 'MA', name: 'Morocco', nameAr: 'المغرب', dialCode: '+212', flag: '🇲🇦', pattern: /^[0-9]{9}$/, timezone: 'Africa/Casablanca' },
//     { code: 'MZ', name: 'Mozambique', nameAr: 'موزمبيق', dialCode: '+258', flag: '🇲🇿', pattern: /^[0-9]{9}$/, timezone: 'Africa/Maputo' },
//     { code: 'MM', name: 'Myanmar', nameAr: 'ميانمار', dialCode: '+95', flag: '🇲🇲', pattern: /^[0-9]{7,10}$/, timezone: 'Asia/Rangoon' },
//     { code: 'NA', name: 'Namibia', nameAr: 'ناميبيا', dialCode: '+264', flag: '🇳🇦', pattern: /^[0-9]{9}$/, timezone: 'Africa/Windhoek' },
//     { code: 'NR', name: 'Nauru', nameAr: 'ناورو', dialCode: '+674', flag: '🇳🇷', pattern: /^[0-9]{7}$/, timezone: 'Pacific/Nauru' },
//     { code: 'NP', name: 'Nepal', nameAr: 'نيبال', dialCode: '+977', flag: '🇳🇵', pattern: /^[0-9]{10}$/, timezone: 'Asia/Kathmandu' },
//     { code: 'NL', name: 'Netherlands', nameAr: 'هولندا', dialCode: '+31', flag: '🇳🇱', pattern: /^[0-9]{9}$/, timezone: 'Europe/Amsterdam' },
//     { code: 'NZ', name: 'New Zealand', nameAr: 'نيوزيلندا', dialCode: '+64', flag: '🇳🇿', pattern: /^[0-9]{8,10}$/, timezone: 'Pacific/Auckland' },
//     { code: 'NI', name: 'Nicaragua', nameAr: 'نيكاراغوا', dialCode: '+505', flag: '🇳🇮', pattern: /^[0-9]{8}$/, timezone: 'America/Managua' },
//     { code: 'NE', name: 'Niger', nameAr: 'النيجر', dialCode: '+227', flag: '🇳🇪', pattern: /^[0-9]{8}$/, timezone: 'Africa/Niamey' },
//     { code: 'NG', name: 'Nigeria', nameAr: 'نيجيريا', dialCode: '+234', flag: '🇳🇬', pattern: /^[0-9]{10}$/, timezone: 'Africa/Lagos' },
//     { code: 'MK', name: 'North Macedonia', nameAr: 'مقدونيا الشمالية', dialCode: '+389', flag: '🇲🇰', pattern: /^[0-9]{8}$/, timezone: 'Europe/Skopje' },
//     { code: 'NO', name: 'Norway', nameAr: 'النرويج', dialCode: '+47', flag: '🇳🇴', pattern: /^[0-9]{8}$/, timezone: 'Europe/Oslo' },
//     { code: 'OM', name: 'Oman', nameAr: 'عُمان', dialCode: '+968', flag: '🇴🇲', pattern: /^[0-9]{8}$/, timezone: 'Asia/Muscat' },
//     { code: 'PK', name: 'Pakistan', nameAr: 'باكستان', dialCode: '+92', flag: '🇵🇰', pattern: /^[0-9]{10}$/, timezone: 'Asia/Karachi' },
//     { code: 'PW', name: 'Palau', nameAr: 'بالاو', dialCode: '+680', flag: '🇵🇼', pattern: /^[0-9]{7}$/, timezone: 'Pacific/Palau' },
//     { code: 'PA', name: 'Panama', nameAr: 'بنما', dialCode: '+507', flag: '🇵🇦', pattern: /^[0-9]{8}$/, timezone: 'America/Panama' },
//     { code: 'PG', name: 'Papua New Guinea', nameAr: 'بابوا غينيا الجديدة', dialCode: '+675', flag: '🇵🇬', pattern: /^[0-9]{8}$/, timezone: 'Pacific/Port_Moresby' },
//     { code: 'PY', name: 'Paraguay', nameAr: 'باراغواي', dialCode: '+595', flag: '🇵🇾', pattern: /^[0-9]{9}$/, timezone: 'America/Asuncion' },
//     { code: 'PE', name: 'Peru', nameAr: 'بيرو', dialCode: '+51', flag: '🇵🇪', pattern: /^[0-9]{9}$/, timezone: 'America/Lima' },
//     { code: 'PH', name: 'Philippines', nameAr: 'الفلبين', dialCode: '+63', flag: '🇵🇭', pattern: /^[0-9]{10}$/, timezone: 'Asia/Manila' },
//     { code: 'PL', name: 'Poland', nameAr: 'بولندا', dialCode: '+48', flag: '🇵🇱', pattern: /^[0-9]{9}$/, timezone: 'Europe/Warsaw' },
//     { code: 'PT', name: 'Portugal', nameAr: 'البرتغال', dialCode: '+351', flag: '🇵🇹', pattern: /^[0-9]{9}$/, timezone: 'Europe/Lisbon' },
//     { code: 'QA', name: 'Qatar', nameAr: 'قطر', dialCode: '+974', flag: '🇶🇦', pattern: /^[0-9]{8}$/, timezone: 'Asia/Qatar' },
//     { code: 'RO', name: 'Romania', nameAr: 'رومانيا', dialCode: '+40', flag: '🇷🇴', pattern: /^[0-9]{9}$/, timezone: 'Europe/Bucharest' },
//     { code: 'RU', name: 'Russia', nameAr: 'روسيا', dialCode: '+7', flag: '🇷🇺', pattern: /^[0-9]{10}$/, timezone: 'Europe/Moscow' },
//     { code: 'RW', name: 'Rwanda', nameAr: 'رواندا', dialCode: '+250', flag: '🇷🇼', pattern: /^[0-9]{9}$/, timezone: 'Africa/Kigali' },
//     { code: 'KN', name: 'Saint Kitts and Nevis', nameAr: 'سانت كيتس ونيفيس', dialCode: '+1869', flag: '🇰🇳', pattern: /^[0-9]{7}$/, timezone: 'America/St_Kitts' },
//     { code: 'LC', name: 'Saint Lucia', nameAr: 'سانت لوسيا', dialCode: '+1758', flag: '🇱🇨', pattern: /^[0-9]{7}$/, timezone: 'America/St_Lucia' },
//     { code: 'VC', name: 'Saint Vincent and the Grenadines', nameAr: 'سانت فنسنت وجزر غرينادين', dialCode: '+1784', flag: '🇻🇨', pattern: /^[0-9]{7}$/, timezone: 'America/St_Vincent' },
//     { code: 'WS', name: 'Samoa', nameAr: 'ساموا', dialCode: '+685', flag: '🇼🇸', pattern: /^[0-9]{5,7}$/, timezone: 'Pacific/Apia' },
//     { code: 'SM', name: 'San Marino', nameAr: 'سان مارينو', dialCode: '+378', flag: '🇸🇲', pattern: /^[0-9]{6,10}$/, timezone: 'Europe/San_Marino' },
//     { code: 'ST', name: 'Sao Tome and Principe', nameAr: 'ساو تومي وبرينسيبي', dialCode: '+239', flag: '🇸🇹', pattern: /^[0-9]{7}$/, timezone: 'Africa/Sao_Tome' },
//     { code: 'SA', name: 'Saudi Arabia', nameAr: 'المملكة العربية السعودية', dialCode: '+966', flag: '🇸🇦', pattern: /^[0-9]{9}$/, timezone: 'Asia/Riyadh' },
//     { code: 'SN', name: 'Senegal', nameAr: 'السنغال', dialCode: '+221', flag: '🇸🇳', pattern: /^[0-9]{9}$/, timezone: 'Africa/Dakar' },
//     { code: 'RS', name: 'Serbia', nameAr: 'صربيا', dialCode: '+381', flag: '🇷🇸', pattern: /^[0-9]{8,9}$/, timezone: 'Europe/Belgrade' },
//     { code: 'SC', name: 'Seychelles', nameAr: 'سيشيل', dialCode: '+248', flag: '🇸🇨', pattern: /^[0-9]{7}$/, timezone: 'Indian/Mahe' },
//     { code: 'SL', name: 'Sierra Leone', nameAr: 'سيراليون', dialCode: '+232', flag: '🇸🇱', pattern: /^[0-9]{8}$/, timezone: 'Africa/Freetown' },
//     { code: 'SG', name: 'Singapore', nameAr: 'سنغافورة', dialCode: '+65', flag: '🇸🇬', pattern: /^[0-9]{8}$/, timezone: 'Asia/Singapore' },
//     { code: 'SK', name: 'Slovakia', nameAr: 'سلوفاكيا', dialCode: '+421', flag: '🇸🇰', pattern: /^[0-9]{9}$/, timezone: 'Europe/Bratislava' },
//     { code: 'SI', name: 'Slovenia', nameAr: 'سلوفينيا', dialCode: '+386', flag: '🇸🇮', pattern: /^[0-9]{8}$/, timezone: 'Europe/Ljubljana' },
//     { code: 'SB', name: 'Solomon Islands', nameAr: 'جزر سليمان', dialCode: '+677', flag: '🇸🇧', pattern: /^[0-9]{7}$/, timezone: 'Pacific/Guadalcanal' },
//     { code: 'SO', name: 'Somalia', nameAr: 'الصومال', dialCode: '+252', flag: '🇸🇴', pattern: /^[0-9]{8,9}$/, timezone: 'Africa/Mogadishu' },
//     { code: 'ZA', name: 'South Africa', nameAr: 'جنوب أفريقيا', dialCode: '+27', flag: '🇿🇦', pattern: /^[0-9]{9}$/, timezone: 'Africa/Johannesburg' },
//     { code: 'SS', name: 'South Sudan', nameAr: 'جنوب السودان', dialCode: '+211', flag: '🇸🇸', pattern: /^[0-9]{9}$/, timezone: 'Africa/Juba' },
//     { code: 'ES', name: 'Spain', nameAr: 'إسبانيا', dialCode: '+34', flag: '🇪🇸', pattern: /^[0-9]{9}$/, timezone: 'Europe/Madrid' },
//     { code: 'LK', name: 'Sri Lanka', nameAr: 'سريلانكا', dialCode: '+94', flag: '🇱🇰', pattern: /^[0-9]{9}$/, timezone: 'Asia/Colombo' },
//     { code: 'SD', name: 'Sudan', nameAr: 'السودان', dialCode: '+249', flag: '🇸🇩', pattern: /^[0-9]{9}$/, timezone: 'Africa/Khartoum' },
//     { code: 'SR', name: 'Suriname', nameAr: 'سورينام', dialCode: '+597', flag: '🇸🇷', pattern: /^[0-9]{6,7}$/, timezone: 'America/Paramaribo' },
//     { code: 'SE', name: 'Sweden', nameAr: 'السويد', dialCode: '+46', flag: '🇸🇪', pattern: /^[0-9]{9,10}$/, timezone: 'Europe/Stockholm' },
//     { code: 'CH', name: 'Switzerland', nameAr: 'سويسرا', dialCode: '+41', flag: '🇨🇭', pattern: /^[0-9]{9}$/, timezone: 'Europe/Zurich' },
//     { code: 'SY', name: 'Syria', nameAr: 'سوريا', dialCode: '+963', flag: '🇸🇾', pattern: /^[0-9]{9}$/, timezone: 'Asia/Damascus' },
//     { code: 'TW', name: 'Taiwan', nameAr: 'تايوان', dialCode: '+886', flag: '🇹🇼', pattern: /^[0-9]{9,10}$/, timezone: 'Asia/Taipei' },
//     { code: 'TJ', name: 'Tajikistan', nameAr: 'طاجيكستان', dialCode: '+992', flag: '🇹🇯', pattern: /^[0-9]{9}$/, timezone: 'Asia/Dushanbe' },
//     { code: 'TZ', name: 'Tanzania', nameAr: 'تنزانيا', dialCode: '+255', flag: '🇹🇿', pattern: /^[0-9]{9}$/, timezone: 'Africa/Dar_es_Salaam' },
//     { code: 'TH', name: 'Thailand', nameAr: 'تايلاند', dialCode: '+66', flag: '🇹🇭', pattern: /^[0-9]{9}$/, timezone: 'Asia/Bangkok' },
//     { code: 'TL', name: 'Timor-Leste', nameAr: 'تيمور الشرقية', dialCode: '+670', flag: '🇹🇱', pattern: /^[0-9]{7,8}$/, timezone: 'Asia/Dili' },
//     { code: 'TG', name: 'Togo', nameAr: 'توغو', dialCode: '+228', flag: '🇹🇬', pattern: /^[0-9]{8}$/, timezone: 'Africa/Lome' },
//     { code: 'TO', name: 'Tonga', nameAr: 'تونغا', dialCode: '+676', flag: '🇹🇴', pattern: /^[0-9]{5,7}$/, timezone: 'Pacific/Tongatapu' },
//     { code: 'TT', name: 'Trinidad and Tobago', nameAr: 'ترينيداد وتوباغو', dialCode: '+1868', flag: '🇹🇹', pattern: /^[0-9]{7}$/, timezone: 'America/Port_of_Spain' },
//     { code: 'TN', name: 'Tunisia', nameAr: 'تونس', dialCode: '+216', flag: '🇹🇳', pattern: /^[0-9]{8}$/, timezone: 'Africa/Tunis' },
//     { code: 'TR', name: 'Turkey', nameAr: 'تركيا', dialCode: '+90', flag: '🇹🇷', pattern: /^[0-9]{10}$/, timezone: 'Europe/Istanbul' },
//     { code: 'TM', name: 'Turkmenistan', nameAr: 'تركمانستان', dialCode: '+993', flag: '🇹🇲', pattern: /^[0-9]{8}$/, timezone: 'Asia/Ashgabat' },
//     { code: 'TV', name: 'Tuvalu', nameAr: 'توفالو', dialCode: '+688', flag: '🇹🇻', pattern: /^[0-9]{5,6}$/, timezone: 'Pacific/Funafuti' },
//     { code: 'UG', name: 'Uganda', nameAr: 'أوغندا', dialCode: '+256', flag: '🇺🇬', pattern: /^[0-9]{9}$/, timezone: 'Africa/Kampala' },
//     { code: 'UA', name: 'Ukraine', nameAr: 'أوكرانيا', dialCode: '+380', flag: '🇺🇦', pattern: /^[0-9]{9}$/, timezone: 'Europe/Kiev' },
//     { code: 'AE', name: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة', dialCode: '+971', flag: '🇦🇪', pattern: /^[0-9]{9}$/, timezone: 'Asia/Dubai' },
//     { code: 'GB', name: 'United Kingdom', nameAr: 'المملكة المتحدة', dialCode: '+44', flag: '🇬🇧', pattern: /^[0-9]{10,11}$/, timezone: 'Europe/London' },
//     { code: 'US', name: 'United States', nameAr: 'الولايات المتحدة', dialCode: '+1', flag: '🇺🇸', pattern: /^[0-9]{10}$/, timezone: 'America/New_York' },
//     { code: 'UY', name: 'Uruguay', nameAr: 'أوروغواي', dialCode: '+598', flag: '🇺🇾', pattern: /^[0-9]{8}$/, timezone: 'America/Montevideo' },
//     { code: 'UZ', name: 'Uzbekistan', nameAr: 'أوزبكستان', dialCode: '+998', flag: '🇺🇿', pattern: /^[0-9]{9}$/, timezone: 'Asia/Tashkent' },
//     { code: 'VU', name: 'Vanuatu', nameAr: 'فانواتو', dialCode: '+678', flag: '🇻🇺', pattern: /^[0-9]{5,7}$/, timezone: 'Pacific/Efate' },
//     { code: 'VE', name: 'Venezuela', nameAr: 'فنزويلا', dialCode: '+58', flag: '🇻🇪', pattern: /^[0-9]{10}$/, timezone: 'America/Caracas' },
//     { code: 'VN', name: 'Vietnam', nameAr: 'فيتنام', dialCode: '+84', flag: '🇻🇳', pattern: /^[0-9]{9,10}$/, timezone: 'Asia/Ho_Chi_Minh' },
//     { code: 'YE', name: 'Yemen', nameAr: 'اليمن', dialCode: '+967', flag: '🇾🇪', pattern: /^[0-9]{9}$/, timezone: 'Asia/Aden' },
//     { code: 'ZM', name: 'Zambia', nameAr: 'زامبيا', dialCode: '+260', flag: '🇿🇲', pattern: /^[0-9]{9}$/, timezone: 'Africa/Lusaka' },
//     { code: 'ZW', name: 'Zimbabwe', nameAr: 'زيمبابوي', dialCode: '+263', flag: '🇿🇼', pattern: /^[0-9]{9}$/, timezone: 'Africa/Harare' },
// ];

// Detect country by browser timezone
export const detectCountryByTimezone = () => {
    try {
        const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        const country = COUNTRIES.find(c => c.timezone === timezone);
        return country || COUNTRIES.find(c => c.code === 'AE') || COUNTRIES[0];
    } catch {
        return COUNTRIES.find(c => c.code === 'AE') || COUNTRIES[0];
    }
};